outcome <- read.csv("ProgAssignment3-data/outcome-of-care-measures.csv", colClasses = "character")
outcome[, 11] <- as.numeric(outcome[, 11])
outcome[, 17] <- as.numeric(outcome[, 17])
outcome[, 23] <- as.numeric(outcome[, 23])
dev.off()
par(mfrow = c(3, 1))
xlim_range <- range(outcome[,11],outcome[,17],outcome[,23],na.rm=TRUE)
hist(outcome[, 11],main="Heart Attack",xlab="30-day Death Rate",xlim=xlim_range)
hist(outcome[, 17],main="Heart Failure",xlab="30-day Death Rate",xlim=xlim_range)
hist(outcome[, 23],main="Pneumonia",xlab="30-day Death Rate",xlim=xlim_range)
par(mfrow = c(1, 3))

hist(outcome[, 11],main="",xlab="30-day Death Rate",xlim=xlim_range,prob= TRUE)
median_11 <- median(outcome[,11],na.rm=TRUE)
mean_11 <- mean(outcome[,11],na.rm=TRUE)
abline(v=median_11,col="red",lwd=2)
title(main=expression("Heart Attack ("*bar(X)*"="))
lines(density(outcome[,11],na.rm=TRUE))

hist(outcome[, 17],main="",xlab="30-day Death Rate",xlim=xlim_range,prob= TRUE)
median_17 <- median(outcome[,17],na.rm=TRUE)
mean_17 <- mean(outcome[,17],na.rm=TRUE)
abline(v=median_17,col="red",lwd=2)
title(main=expression("Heart Failure ("*bar(X)*"=)"))
lines(density(outcome[,17],na.rm=TRUE))

hist(outcome[, 23],main="",xlab="30-day Death Rate",xlim=xlim_range,prob= TRUE)
median_23 <- median(outcome[,23],na.rm=TRUE)
mean_23 <- mean(outcome[,23],na.rm=TRUE)
lines(density(outcome[,23],na.rm=TRUE))
abline(v=median_23,col="red",lwd=2)
title(main=expression("Pneumonia("*bar(X)*"=)"))